version: "3.9"
services:
  backend:
    container_name: backend
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend/:/home/app
    environment:
      - PORT_BACKEND=3000
    links:
      - database
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - ../database:/data/db
  express:
    image: mongo-express
    container_name: express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - database